<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <title>Riverside Rocks</title>\n";
echo "  <link\n";
echo "    rel=\"stylesheet\"\n";
echo "    type=\"text/css\"\n";
echo "    href=\"https://cdnjs.cloudflare.com/ajax/libs/CSS-Mint/2.0.7/css-mint.min.css\"\n";
echo "  />\n";
echo "  <link\n";
echo "    rel=\"icon\"\n";
echo "    type=\"image/png\"\n";
echo "    href=\"https://cdn.glitch.com/bf0767d5-0a69-4254-b815-2eafc67edd33%2FScreenshot%202020-01-18%20at%2011.47.23%20AM.png?v=1581255936266\"\n";
echo "  />\n";
echo "  <link rel=\"stylesheet\" type=\"text/css\" href=\"/style.css\" />\n";
echo "  <style>\n";
echo "    a {\n";
echo "      color: inherit;\n";
echo "      text-decoration: none;\n";
echo "    }\n";
echo "  </style>\n";
echo "  <header class=\"cm-header inverted\">\n";
echo "    <div class=\"cm-logo cm-text-large\">\n";
echo "      <a\n";
echo "        href=\"/blog\"\n";
echo "        style=\"font-size:55px;padding:7px;line-height:-25px;margin:29px;height:200px;\"\n";
echo "        >Riverside Rocks</a\n";
echo "      >\n";
echo "    </div>\n";
echo "    <nav class=\"cm-nav\">\n";
echo "      <ul>\n";
echo "        <li>\n";
echo "          <button\n";
echo "            style=\"background-color:black;font-size:30px;text-decoration:none;border:none;display:inline-block;font-size:24px;\"\n";
echo "          >\n";
echo "            <a\n";
echo "              href=\"/#\"\n";
echo "              style=\"font-size:30px;text-decoration:none;border:none;display:inline-block;padding:12px;font-size:24px;\"\n";
echo "              >Home</a\n";
echo "            >\n";
echo "          </button>\n";
echo "        </li>\n";
echo "        <li>\n";
echo "          <button\n";
echo "            style=\"background-color:black;font-size:30px;text-decoration:none;border:none;display:inline-block;font-size:24px;\"\n";
echo "          >\n";
echo "            <a\n";
echo "              href=\"/#main\"\n";
echo "              style=\"font-size:30px;text-decoration:none;border:none;display:inline-block;padding:12px;font-size:24px;\"\n";
echo "              >About</a\n";
echo "            >\n";
echo "          </button>\n";
echo "        </li>\n";
echo "        <li>\n";
echo "          <button\n";
echo "            style=\"background-color:black;font-size:30px;text-decoration:none;border:none;display:inline-block;font-size:24px;\"\n";
echo "          >\n";
echo "            <a\n";
echo "              href=\"/#work\"\n";
echo "              style=\"font-size:30px;text-decoration:none;border:none;display:inline-block;padding:12px;font-size:24px;\"\n";
echo "              >Projects</a\n";
echo "            >\n";
echo "          </button>\n";
echo "        </li>\n";
echo "        <li>\n";
echo "          <button\n";
echo "            style=\"background-color:black;font-size:30px;text-decoration:none;border:none;display:inline-block;font-size:24px;\"\n";
echo "          >\n";
echo "            <a\n";
echo "              href=\"/#contact\"\n";
echo "              style=\"font-size:30px;text-decoration:none;border:none;display:inline-block;padding:12px;font-size:24px;\"\n";
echo "              >Contact</a\n";
echo "            >\n";
echo "          </button>\n";
echo "        </li>\n";
echo "      </ul>\n";
echo "    </nav>\n";
echo "  </header>\n";
echo "  <br />\n";
echo "  <br />\n";
echo "  <center>\n";
echo "    <h2>\n";
echo '' . htmlspecialchars($_GET["title"]) . '';
echo "    </h2>\n";
echo "    <br />\n";
echo "    <br />\n";
echo "    <div style=\"width:55%;line-height:35px;\">\n";
echo "        <h3>\n";
echo '<strong>Today - </strong> ' . htmlspecialchars($_GET["content"]) . '';
echo "        </h3>\n";
echo "      </div>\n";
echo "      <h5>Built with the Riverside Rocks article maker.</h5>";

?>
